#!/bin/bash
set -e -u

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

if [ ${DB:-"none"} = "mysql" ]; then
  echo "running tests with MYSQL"
  docker run --privileged \
     --rm \
     -it \
     -v $PWD:/go/src/code.cloudfoundry.org/silk \
     -e GOPATH=/go \
     -e MYSQL=true \
     -w /go/src/code.cloudfoundry.org/silk \
     c2cnetworking/dev-mysql \
     ./scripts/test.sh "$@"
elif [ ${DB:-"none"} = "postgres" ]; then
  echo "running tests with POSTGRES"
  docker run --privileged \
     --rm \
     -it \
     -v $PWD:/go/src/code.cloudfoundry.org/silk \
     -e GOPATH=/go \
     -e POSTGRES=true \
     -w /go/src/code.cloudfoundry.org/silk \
     c2cnetworking/dev-postgres \
     ./scripts/test.sh "$@"
elif [ ${DB:-"foo"} = "none" ]; then
  echo "running tests without a database"
  docker run --privileged \
     --rm \
     -it \
     -v $PWD:/go/src/code.cloudfoundry.org/silk \
     -e GOPATH=/go \
     -e POSTGRES=false \
     -w /go/src/code.cloudfoundry.org/silk \
     c2cnetworking/dev-postgres \
     ./scripts/test.sh "$@"
else
  export DB=postgres
  "$0" "$@"
fi
