#!/bin/bash
set -e -u

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

db=${DB:-"postgres"} # if not set, default to postgres

docker_image=cloudfoundry/tas-runtime-$db
if [ $db = "none" ]; then
  docker_image=cloudfoundry/tas-runtime-build
fi

docker run \
   --rm \
   -it \
   --privileged \
   -v $PWD:/silk \
   -e DB=$db \
   -w /silk \
   $docker_image \
   /bin/bash "$@"
