#!/bin/bash
set -e -u

ROOT_DIR_PATH=$(cd $(dirname $0)/.. && pwd)
cd $ROOT_DIR_PATH

db=${DB:-"postgres"} # if not set, default to postgres

docker_image=c2cnetworking/dev-$db
if [ $db = "none" ]; then
  docker_image=c2cnetworking/dev-postgres
fi

docker run \
   --rm \
   -it \
   --privileged \
   -v $PWD:/silk \
   -e DB=$db \
   -w /silk \
   $docker_image \
   /bin/bash "$@"
