// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/containernetworking/cni/pkg/ns"
)

type NamespaceAdapter struct {
	GetNSStub        func(string) (ns.NetNS, error)
	getNSMutex       sync.RWMutex
	getNSArgsForCall []struct {
		arg1 string
	}
	getNSReturns struct {
		result1 ns.NetNS
		result2 error
	}
	getNSReturnsOnCall map[int]struct {
		result1 ns.NetNS
		result2 error
	}
	GetCurrentNSStub        func() (ns.NetNS, error)
	getCurrentNSMutex       sync.RWMutex
	getCurrentNSArgsForCall []struct{}
	getCurrentNSReturns     struct {
		result1 ns.NetNS
		result2 error
	}
	getCurrentNSReturnsOnCall map[int]struct {
		result1 ns.NetNS
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *NamespaceAdapter) GetNS(arg1 string) (ns.NetNS, error) {
	fake.getNSMutex.Lock()
	ret, specificReturn := fake.getNSReturnsOnCall[len(fake.getNSArgsForCall)]
	fake.getNSArgsForCall = append(fake.getNSArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("GetNS", []interface{}{arg1})
	fake.getNSMutex.Unlock()
	if fake.GetNSStub != nil {
		return fake.GetNSStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getNSReturns.result1, fake.getNSReturns.result2
}

func (fake *NamespaceAdapter) GetNSCallCount() int {
	fake.getNSMutex.RLock()
	defer fake.getNSMutex.RUnlock()
	return len(fake.getNSArgsForCall)
}

func (fake *NamespaceAdapter) GetNSArgsForCall(i int) string {
	fake.getNSMutex.RLock()
	defer fake.getNSMutex.RUnlock()
	return fake.getNSArgsForCall[i].arg1
}

func (fake *NamespaceAdapter) GetNSReturns(result1 ns.NetNS, result2 error) {
	fake.GetNSStub = nil
	fake.getNSReturns = struct {
		result1 ns.NetNS
		result2 error
	}{result1, result2}
}

func (fake *NamespaceAdapter) GetNSReturnsOnCall(i int, result1 ns.NetNS, result2 error) {
	fake.GetNSStub = nil
	if fake.getNSReturnsOnCall == nil {
		fake.getNSReturnsOnCall = make(map[int]struct {
			result1 ns.NetNS
			result2 error
		})
	}
	fake.getNSReturnsOnCall[i] = struct {
		result1 ns.NetNS
		result2 error
	}{result1, result2}
}

func (fake *NamespaceAdapter) GetCurrentNS() (ns.NetNS, error) {
	fake.getCurrentNSMutex.Lock()
	ret, specificReturn := fake.getCurrentNSReturnsOnCall[len(fake.getCurrentNSArgsForCall)]
	fake.getCurrentNSArgsForCall = append(fake.getCurrentNSArgsForCall, struct{}{})
	fake.recordInvocation("GetCurrentNS", []interface{}{})
	fake.getCurrentNSMutex.Unlock()
	if fake.GetCurrentNSStub != nil {
		return fake.GetCurrentNSStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getCurrentNSReturns.result1, fake.getCurrentNSReturns.result2
}

func (fake *NamespaceAdapter) GetCurrentNSCallCount() int {
	fake.getCurrentNSMutex.RLock()
	defer fake.getCurrentNSMutex.RUnlock()
	return len(fake.getCurrentNSArgsForCall)
}

func (fake *NamespaceAdapter) GetCurrentNSReturns(result1 ns.NetNS, result2 error) {
	fake.GetCurrentNSStub = nil
	fake.getCurrentNSReturns = struct {
		result1 ns.NetNS
		result2 error
	}{result1, result2}
}

func (fake *NamespaceAdapter) GetCurrentNSReturnsOnCall(i int, result1 ns.NetNS, result2 error) {
	fake.GetCurrentNSStub = nil
	if fake.getCurrentNSReturnsOnCall == nil {
		fake.getCurrentNSReturnsOnCall = make(map[int]struct {
			result1 ns.NetNS
			result2 error
		})
	}
	fake.getCurrentNSReturnsOnCall[i] = struct {
		result1 ns.NetNS
		result2 error
	}{result1, result2}
}

func (fake *NamespaceAdapter) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.getNSMutex.RLock()
	defer fake.getNSMutex.RUnlock()
	fake.getCurrentNSMutex.RLock()
	defer fake.getCurrentNSMutex.RUnlock()
	return fake.invocations
}

func (fake *NamespaceAdapter) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}
